spring:
  application:
    name: TPO_12
  h2:
    console:
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:blog
    username: s30855
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

