spring:
  application:
   name: TPO_TEST_02
  h2:
   console:
    path: /h2-console
  datasource:
   url: jdbc:h2:mem:test
   username: sa
   password:
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
   defer-datasource-initialization: true
